name: Download Site

on:
  workflow_dispatch:
    inputs:
      site_url:
        description: 'Website URL'
        required: true
        type: string

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Download
        run: |
          wget -r -k -p -E -np -e robots=off "${{ github.event.inputs.site_url }}" || true
      
      - name: Zip
        run: |
          sudo apt-get install -y zip
          zip -r -s 95m backup.zip ./
      
      - name: Push
        run: |
          git config user.name "bot"
          git config user.email "bot@users.noreply.github.com"
          git add backup.zip*
          git commit -m "Add website backup" || true
          git push
